### ISSUE TITLE
resize doesn't make change immediately

### ISSUE THREAD

**Issue by zhaoyi0113** [Tyriar/node-pty#166]
I call resize on pty process but it doesn't make any difference for the next input command. It only works for the second command I send through. See below example:

```
ptyProcess.resize(10000, 30)
ptyProcess.write(cmd); // it still uses the old size
ptyProcess.write(cmd); // it uses the new size
```

**Comment by Tyriar** [comment]
Provided you're talking about Linux/macOS, it looks like everything should be synchronous, but looks like the communication between node and the pty is not. In order to guarentee the change occurred, you might need to listen for the `SIGWINCH` signal?

> When the window size changes, a SIGWINCH signal is sent to the foreground process group.

https://linux.die.net/man/4/tty_ioctl

Closing as I don't have any plans to change this.
