### ISSUE TITLE
Quoting args doesn't work as expected on Windows

### ISSUE THREAD

**Issue by Tyriar** [Tyriar/node-pty#41]
Downstream issue: https://github.com/Microsoft/vscode/issues/19078

`argvToCommandLine` makes the following transformation:

```
cmdline: cmd.exe,/c,dir "a b"
cmdlineFlat: cmd.exe /c "dir \"a b\""
```

**Comment by Tyriar** [comment]
@the-ress any feedback on https://github.com/Tyriar/node-pty/commit/28be849c023b14758c828409d963cd3a951bbb57 would be appreciated :smiley:

**Comment by the-ress** [comment]
The problem is that every application can parse the command line differently. The current implementation works well with applications that use [`CommandLineToArgvW`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx) or compatible implementation (node.js and C# applications among others). `cmd.exe` or batch files handle arguments differently.

So 28be849 breaks escaping for the first group of applications. I would solve the problem in Microsoft/vscode#19078 by using `["dir", "test folder"]` because that works too, but I can't think think of any universal solution.

**Comment by Tyriar** [comment]
The issue with ["dir", "test folder"] is it's 2 args though so it might behave differently. If the command required escaping within an arg could you not just specify args as `["dir \\"test folder\\""]`?

Do you have an example command/args where the change would fail?

**Comment by TSlivede** [comment]
@Tyriar 
I think https://github.com/Tyriar/node-pty/commit/28be849c023b14758c828409d963cd3a951bbb57 should definitely be reverted:

When calling an executable with an array of argument, almost every CLI-App splits this Commandline according to [these](https://msdn.microsoft.com/en-us/library/17w5ykft.aspx) rules (the only exception I currently know of, is old legacy cmd.exe). Therefore the Commandline should be build in a way, that matches those rules.

Many modern Commandshells on windows do this:
- https://www.hamiltonlabs.com/Cshell.htm (not documented)
- [Cygwin](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=blob;f=winsup/cygwin/winf.cc;hb=HEAD) (see `linebuf::fromargv`)
- [Python](https://svn.python.org/projects/python/trunk/Lib/subprocess.py) (see `list2cmdline`)
- [Tcl](https://github.com/tcltk/tcl/blob/master/win/tclWinPipe.c) (see `BuildCommandLine`, Comment: "N backslashes followed a quote -> insert N * 2 + 1 backslashes then a quote.")

To solve the problem with cmd, one could allow passing a string as `args` instead of an array.
The current solution is very inconsistent (backslashes are escaped, quotes not?). If it is really desired, to let the user quote arguments himself, `argvToCommandLine` should be completely removed, so the user must enquote and escape the arguments by himself.

**Comment by Tyriar** [comment]
Thanks for the detailed explanation @TSlivede, makes sense. I was holding off on release until I got someone who knows more about the area to confirm :smile: I'll probably allow args as a string as you suggest:

```ts
export function fork(file?: string, args?: string | string[], opt?: IPtyForkOptions): ITerminal
```

**Comment by TSlivede** [comment]
@Tyriar Very nice!! 👍 👍 👍 
Althought I'd call it `ArgsOrCmdline` or similar instead of `ArgsOrArgv`.
Both `args` and `argv` are names for Argument-arrays. :smiley:
[CommandLine](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683156.aspx) or CmdLine is the Microsoft terminology for the single argument-string.

**Comment by Tyriar** [comment]
Sounds good :+1:

**Comment by TSlivede** [comment]
Just another note: To solve the problem in https://github.com/Microsoft/vscode/issues/19078, one could simply replace cmd by powershell and it should work.
Btw: This (with powershell) is one case that breaks with https://github.com/Tyriar/node-pty/commit/28be849c023b14758c828409d963cd3a951bbb57 😄

**Comment by Tyriar** [comment]
Fixed in https://github.com/Tyriar/node-pty/pull/47
