### ISSUE TITLE
Example how to use it in an Electron app

### ISSUE THREAD

**Issue by stoffeastrom** [Tyriar/node-pty#55]
When I try to `fork` or `spawn` in an Electron app I get

```
Error: Could not call remote function 'fork'. Check that the function signature is correct. Underlying error: Path must be a string. Received [Function: callIntoRenderer]
```

**Comment by Tyriar** [comment]
Looks like you're passing in the wrong arguments somehow? I'd need to see the specific call.

On explaining how to use, I try to do this on the README by suggesting a project I also maintain xterm.js:

> Writing a terminal emulator (eg. via xterm.js)

Which contains a usage example as a demo https://github.com/sourcelair/xterm.js, could probably also do something here to show how to make a simple Electron terminal app using node-pty and xterm.js.

**Comment by Tyriar** [comment]
You can check out exactly how I do it in VS Code here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js

Note that `terminalProcess.js` is being launched as its own process in order to work around the following Electron bug https://github.com/electron/electron/issues/38, terminalProcess.js is launched like this https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L38

Nothing looks particularly bad with your current setup, maybe something is going wrong in the way you're transferring the data between node-pty and xterm.js? I expect something like this:

```js
xterm.on('data', (data) => {
  pty.write(data);
});
pty.on('data', function (data) {
  xterm.write(data);
});
```

**Comment by stoffeastrom** [comment]
Cool, I will have a look!

**Comment by stoffeastrom** [comment]
Holy moly! it just worked 🚀

**Comment by stoffeastrom** [comment]
I saw that you used the form

```
import cp = require('child_process');
```
So I changed my so suddenly I got typescript help and I had ofc an error

`process.cwd` vs `process.cwd()` hence the error message.

Thank for this great library!

**Comment by Tyriar** [comment]
Great! 😄

**Comment by Tyriar** [comment]
@stoffeastrom while making an electron example I ran into exactly what you hit with `process.cwd` so I added an exception to give a better error :stuck_out_tongue: https://github.com/Tyriar/node-pty/commit/4ad2860a48bb2980cfd4044c72346531bb578a9d

**Comment by Tyriar** [comment]
@stoffeastrom thanks for the suggestion, added the example to https://github.com/Tyriar/node-pty/tree/master/examples/electron
