### ISSUE TITLE
I got an error on compiling

### ISSUE THREAD

**Issue by adispartadev** [Tyriar/node-pty#69]
`Error: The module '/home/dev/Documents/project/node_web_kit/node_modules/node-pty/build/Release/pty.node' was compiled against a different Node.js version using 
NODE_MODULE_VERSION 46. This version of Node.js requires 
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing`

I have tried `npm rebuild` but didn't work. Any solution?

**Comment by Tyriar** [comment]
@adispartadev this means you're installing node-pty using the wrong version of V8 (probably the local `node` on the `PATH`). If you're using Electron this script demonstrates how you build using Electron rather than the installed version of node https://github.com/Tyriar/node-pty/blob/master/examples/electron/npm_install.sh

**Comment by adispartadev** [comment]
Thanks, the example one is working
